- build.sh
- buildroot.sh
- update.sh
this will hopefully make sure bash is used to run the build scripts
> Changed shebang lines to use env

- .gitignore
- build.sh
- clean.sh
- scripts/etc/init.d/rcS
- update.sh
The kernel upgrade script (https://github.com/debian-pi/raspbian-tools/blob/master/raspbian-kernel-post-install) isn't ready yet, but I think the part of the installer is.
> Add support for rpi2

- CHANGELOG.md
- README.md
- build.sh
- buildroot.sh
I plan to mention on the release page the following issues:
- the kernel sometimes still crashes with a reference to https://github.com/raspberrypi/linux/issues/914
- the issue with the power LED (https://github.com/debian-pi/raspbian-ua-netinst/issues/207
(unless you object)
> Prepare 1.0.7 release

- update.sh
Reduces runtime of update.sh from 90s to 30s (on my test machine)
Requires bash 4.x
> Optimizied search for required packages in package list

- update.sh
This is a backport of https://github.com/debian-pi/raspbian-ua-netinst/pull/236 to the v1.0.x branch.
> Applied Zeerix' PR #236 to the v1.0.x branch.

- scripts/etc/init.d/rcS
- Fixed a path
- Fixed test if copy was successful
- Removed unneccessary test for success
> Fixed some tests in the installer.

- BUILD.md
- CHANGELOG.md
- README.md
- build.sh
- buildroot.sh
- scripts/etc/init.d/rcS
- update.sh
The branches were getting rather out of sync, this PR fixes that.
> Merge changes from 1.0 into 1.1

- scripts/etc/init.d/rcS
This allows the user to specify the amount of sectors at the beginning of the sd card to keep free before the first partition.
I expect this will provide a solution to issue #299 and maybe even #283
> Add bootoffset parameter

- README.md
- scripts/etc/init.d/rcS
> Added option to set amount of memory to use by the GPU.

- scripts/etc/init.d/rcS
Implemented most suggesting that http://www.shellcheck.net/ indicated.
I left some items unresolved as they're rather debatable, which we of course can do :wink:
> Fixed various shellcheck issues

- CONTRIBUTING.md
- README.md
* typos
* whitespace (automagically fixed by Atom)
* issue #357
* increased readability of the options descriptions
> Fixing documentation

- scripts/etc/init.d/rcS
Pretty much the same thing as #381, just for the v1.1.x branch
one thing that's added is a check (and removal) for 127.0.1.1, as the script sets this later on.
> Single loopback for v1.1.x

- README.md
- scripts/etc/init.d/rcS
> Add option to disable predictable names

- README.md
- scripts/etc/init.d/rcS
> Add watchdog functionality

- README.md
- config/my-files.list
- scripts/etc/init.d/rcS
Allow end-user to supply custom files.
User supplied files are added to the target system during install.
> Overlay target system

- build.sh
- update.sh
> Updated kernel version to 4.4 for v1.0.x branch

- build.sh
- scripts/etc/init.d/rcS
> pi zero support

- scripts/etc/init.d/rcS
see https://github.com/debian-pi/raspbian-ua-netinst/pull/418#r77345654
> fix enable_uart=1 to enable the serial console

- scripts/etc/init.d/rcS
make defined hostname available via `hostname` command during installation
> fix #456 tell kernel hostname

- scripts/etc/init.d/rcS
Same code, now in correct place.
Sorry I didn't correct PR #491 before it was merged, but I thought it was being ignored.
> Don't override consoleblank=0 - correct PR #491
