debian-pi/raspbian-ua-netinst

- README.md
It was unclear to me that you could place the installer-config.txt on the sdcard without building your own install.  I tried to make it more clear. I think it just needs to be mentioned explicitly in the readme file.
> Updated readme.md to make more clear

- README.md
- build.sh
- config/apt/sources.list
- scripts/etc/init.d/rcS
- update.sh
User must add wpa_supplicant.conf file to /boot/config/ which is in wpa_supplicant-format, see man wpa_supplicant.conf.
Added following options and added it to readme
ifname - interface name used for network connection
wlandriver - filename of driver which is inserted into the kernel. This file must exist in the default installation.
Installation now includes wpa_supplicant and firmware-realtek package.
Directory /drivers/wireless holds wlan drivers
> Added configuration for installing over wifi

- build.sh
When the output filename is the same as the input filename, only the
path is specified for the output.
This was done in some places before and now in all.
> Harmonized the various copy statements.

- update.sh
As ShiftPlusOne confirmed the key details via a signed message, posted
on http://pastebin.com/8UaWvHRZ and copied 'locally' here:
https://github.com/debian-pi/raspbian-ua-netinst/issues/64#issuecomment-99134357
I now consider the downloading of the raspberrypi.org signing key
secure.
This fixes issue #64.
> Fixed the download of the raspberry.org GPG key to be from a secure URL.

- update.sh
The `--import` command can be used to import keyrings in addition to individual keys, so it is necessary to check that only the two desired keys were imported. (Subsequent signature verifications depend on only valid keys being in the default keyring.)
The current version is vulnerable to attackers who can MITM HTTPS connections, because the attacker could replace `raspbian.public.key` with a keyring containing both `raspbian.public.key` and the attacker's key, then sign malicious files with their own key. The `update.sh` script would check that `raspbian.public.key` was imported but not notice the presence of the attacker's key. This commit prevents this vulnerability by ensuring that only the two desired keys were imported.
> Verify the number of imported GPG keys

- build.sh
On cpio build, the drivers for both kernels (rpi1, rpi2) were mixed up
> Fixed bug in copying wireless drivers

- BUILD.md
we use bc in buildroot.sh, but it's not installed on a Ubuntu server 15.04 system
> Add dependency to BUILD.md

- build.sh
- clean.sh
When gzipped, the files are about half the size. This leaves more space in /boot.
See also #238
> Adding gzip compression of installer cpio files

- update.sh
This just has a cosmetic effect.
Old output:
```
Checking key file 'raspbian.public.key'... gpg: keyring `gnupg/secring.gpg' created
gpg: keyring `gnupg/pubring.gpg' created
gpg: gnupg/trustdb.gpg: trustdb created
OK
Importing 'raspbian.public.key' into keyring... OK
```
New output:
```
Checking key file 'raspbian.public.key'... OK
Importing 'raspbian.public.key' into keyring... OK
```
> Improved output of checks by triggering the first invocation before we actually use it.

- scripts/etc/init.d/rcS
* rootfstype can now be changed in online_config. previously, the mount options would be wrong for the new filesystem.
* if mkfs failed for the rootfs, the SD/microSD card was unbootable, because the bootloader was only copied back after that step. with this PR, the bootloader files are copied back earlier.
> Improved support for rootfstype option

- scripts/etc/init.d/rcS
This PR re-implements the presets configuration so that a kernel is always installed as well as `cpufrequtils` to fully utilize the CPU.
This fixes #253, #277, #279 and #271.
> Fix presets

- config/apt/raspberrypi.org.list
This is essentially the same change as commit
1dfa5f2b338e14df7d84b19bbcf278d0be1b48bc but adjusted for the 1.1.x branch.
> Replaced 'wheezy' with __RELEASE__ for the raspberrypi.org repo.

- scripts/etc/init.d/rcS
This allow to remotely connect to a setup via SSH for root and the custom user. It also modifies sudoers.d in case a password was not set so that sudo can still be accomplished.
> Correct user creation for remote SSH administration

- README.md
Copy and paste "installer‑config.txt" in the GitHub REAMDE.md page will
lead the installer to ignore the file since it expects
"installer-config.txt" instead.
Yeah, I'm a lazy person.
> Replace non-breaking hyphen ('‑' / &#8209;) by hyphen-minus ('-') for "installer-config.txt"

- README.md
Suggest removing the read-permissions on swap-file. Without, it was left world-readable, allowing other users to read the swap-file.
> Security suggestion on swap permissions

- README.md
- scripts/etc/init.d/rcS
This lets you specify what to do at the end of the install (reboot / poweroff / halt).
Useful when using the installer to build an installed image; you don't want to actually boot into the installed system before you've taken a copy of the installed image.
> Allow poweroff or halt after installing

- scripts/etc/init.d/rcS
This helps if post-install wants to do package operations that would
usually invoke rc.d scripts.
> Move the removal of cdebootstrap-helper-rc.d later, after post-install

- README.md
- scripts/etc/init.d/rcS
This allows configuring the Pi version to target from the installer config, and also allows targetting both Pi1 & Pi2 together. (I am using the installer to build an installed image that will then be run on many different machines, so it needs to support both).
Should cover #194 too.
> Add a way to specify the target hardware to install for

- scripts/etc/init.d/rcS
The 'base' preset doesn't install the ssh-server package and thus also
doesn't have the sshd_config file.
> Added check for existence of file before operating on it.

- config/apt/sources.list
Components from 'non-free' may need programs from contrib, thus add it.
The new ordering is also more logical/standard.
> Added 'contrib' to the archive areas list and reordered the sequence.

- README.md
It should be 'chmod', not 'chown'. Thanks to gitdings for bringing it to
our attention.
> Fixed error in security setting swap file.

- scripts/etc/init.d/rcS
This is useful if you want to manage the keyrings as separate files rather than bundling the keys into the main keyring.
> Allow installing entire gpg keyrings into /etc/apt

- scripts/etc/init.d/rcS
The problem is that the tee might not have finished writing out the end of the logfile when the copy/umount happens. I find it usually cuts off at least the "installation finished at .." line.
This is a bit of a bandaid - the "right" solution would be to preserve the original console fds at the start of the install, switch back to them at the end, close the pipe and wait for the tee to exit - but it's much simpler and seems to work OK.
> Sleep before unmounting to make the logfile more likely to be complete.

- scripts/etc/init.d/rcS
Without fsck.vfat, fsck of /boot is silently skipped on boot.
> Add dosfstools to minimal packages for fsck.vfat.

- scripts/etc/init.d/rcS
Turns out it was only needed on files related to locales.
I thought also about `date +"%Y-%m-%d %H:%M:%S" > /rootfs/etc/fake-hwclock.data`, but decided against it as it won't generate an error (`fake-hwclock` may not be installed).
> Check for existence of locale files/programs before operating on them.

- build.sh
There are various network devices which run over USB, besides wireless,
and they should now work too. Probably (also) useful for the Pi Zero.
> Added 'drivers/net/usb' to support network devices over usb.

- config/apt/01vcgencmd.pref
The 'n' (name) parameter doesn't distinguish between the raspbian.org repo 
and the raspberrypi.org repo as they both have wheezy and jessie.
But in the raspberrypi.org repo it is contained in the 'main' section
whereas it is in the firmware section of raspbian.org.
Bonus side effect is that if you switch to stretch (=current testing)
after having installed jessie first, then it still works.
> Changed Pin condition to 'c=firmware' as that is a better differentiator.

- build.sh
Many executables copied into the initramfs are dynamically linked,
and have an embedded path to the linker/loader that should be used
to execute them. This patch adds a symbolicy link in that location
which points to the actual location in the initramfs.
> Provide dynamic linker in expected location

- scripts/etc/udhcpc/default.script
The udhcpc script uses various 'ip' commands to manipulate the IP
addresses during installation; this patch ensures that the commands
only affect the IPv4 (family 'inet') addresses and routes, thus
avoiding removal of IPv6 addresses added by the kernel or other
processes.
> Ensure 'ip' commands run by udhcpc only affect IPv4 addresses

- scripts/etc/init.d/rcS
It seems Wheezy adds a lo interface to `/etc/network/interfaces`, this PR adds a check, which prevents the script from adding another one in such case
> Add check for existing lo interface

- README.md
- scripts/etc/init.d/rcS
If a `rcS` file is found in the config directory of the SD card, the installer (`rcS`) script will execute that file instead of itself.
This allows for much easier installer development, as there is no need to rebuild the installer image every time a change needs to be tested.
As a side effect, it also allows end users to add to (or change) the installer script without a need to rebuild the image.
> Run alternative rcS, if present

- scripts/etc/init.d/rcS
This one is related to #388 but fixed the hostname issue for v1.0.x
It adds a trailing newline (well, just removed the option that prevented it from being created) to `/etc/hostname`
> Add trailing newline to /etc/hostname

- scripts/etc/init.d/rcS
It adds a newline to `/etc/hostname` (same will be done for v1.0.x)
In addition to this, `/etc/hosts` gets generated in a different way and afterwards contains needed entries
Fixes #387
> Fix hosts file creation

- scripts/etc/init.d/rcS
Changes:
1. Put all networking related code together.
2. If `config/wpa_supplicant.conf` exists AND was used by the installer then copy it to the installed system in `/etc/wpa_supplicant/` and add a reference to it in `/etc/network/interfaces`.
3. Changed the way of installing and starting `wpa_supplicant` so that it actually works.
This commit will allow the user to **install** AND **use** the target system in the absence of a wired ethernet connection, but in the presence of a WiFi network.
The user must configure the following (already existing) parameters:
1. `drivers_to_load=` supply the name of the module that must be loaded by the kernel for the hardware (WiFi dongle) used. _E.g.: `8192cu`_.
1. `ifname=` supply the non-ethernet interface name. Normally you will use `wlan0` here. …
> wpa_supplicant usage

- build.sh
- scripts/etc/init.d/rcS
- update.sh
Currently you can't build an installer that boots due to incompatibility between the new firmware files and the 3.18 kernel. This PR fixes that.
> Kernel 4.4 update

- README.md
If the user has not overridden it, hwrng_support is on by default, and the
rng-tools package will be installed. In addition, in current kernels the
hwrng driver is in the kernel, not delivered as a module. If the user *has*
overridden the hwrng_support default, they don't need a note about how to
install rng-tools because they presumably did that on purpose :-)
> Remove note about installing rng-tools as hwrng_support is on by default

- README.md
- build.sh
- scripts/etc/init.d/rcS
- update.sh
This patch adds substantial support for use of IPv6 in the installer,
and in the installed system. It supports static configuration, although
most IPv6 networks use automatic (and dynamic) configuration. This
patch does not provide DHCPv6 support as there is no suitable DHCPv6
client available to use in the installer's environment, but it does
provide support for Router Advertisements, SLAAC, and RDNSS.
In order to simplify management of DNS resolver information in the
installed system (since there are multiple potential sources of this
information), this patch adds the 'resolvconf' package to the installed
system. If IPv6 DNS information is gathered from RDNSS, the 'rdnssd'
package will also be added to the installed system.
For discovery of Router Advertisment-provided information …
> Add IPv6 support

- buildroot.sh
I've updated the 'buildroot.sh' script so that it automatically finds the next free loop device and does not always try and use /dev/loop0.
> Find the first unused loop device.

- README.md
When copy-and-paste the filename post‑install.txt you get an error while installing, because the hyphen was written as a special character.
Copying /boot files in... cp: can't create '/boot/post?install.txt': Invalid argument
> change special character in README #453

- update.sh
Reduces runtime of update.sh from 40s to 18s (home PC) or 38s to 11s (Cloud VM).
> Optimized search for required packages in package list using awk

- build.sh
- scripts/etc/init.d/rcS
It was build-in with kernel 4.4, but with 4.9 it is once again build as
a kernel module (like it was before 4.4).
> Add HWRNG kernel module back and explicitly load the module.

- build.sh
Avoid kernel panic on boot of RPi3.
With current kernel and firmware, we probably have to enable UART by a device tree overlay.
> Disable UART for the installer

- build.sh
- scripts/etc/init.d/rcS
- scripts/etc/modprobe.d/blacklist-native-rtl8192.conf
* Blacklisting kernel module rtl8192cu, as it does not work properly and binds to the wireless device, preventing from loading 8192cu.
* Adding cfg80211.ko to the initramfs, as it is needed for the driver 8192cu with the current kernel (also needed for RPi3 onboard WLAN, see #470)
> Blacklist rtl8192cu, let mdev use 8192cu instead

- build.sh
- scripts/etc/init.d/rcS
- update.sh
Request for comments: What needs to be changed to get pulled?
I got my hands on a RPi3 and after some tinkering, I got the installation over onboard WLAN to work.
While adding to much firmware to this installer probably wouldn't be a good idea, the Pi 3 and the Zero W seem to have the same chip (brcm43430), and supporting the official Raspberry chipsets would be reasonable.
However, the firmware package in Raspbian is too old, we need the one from raspberrypi.org. If that would be ok, I would add that as second download mirror (like this fork does: https://github.com/FooDeas/raspberrypi-ua-netinst ).
> Added firmware and modules for the wlan on RPi3 and ZeroW

- build.sh
- update.sh
Changed both update.sh and build.sh kernel versions to 4.9.0-3 due 4.9.0-2 exist no more in upstream.
Signed-off-by: Sami Olmari <sami@olmari.fi>
> Changed kernel to 4.9.0-3

- README.md
- scripts/etc/init.d/rcS
This rather simple change eliminates what, to me, is the most irritating problem for blind installs.
For those who run blind installs with no intention of ever connecting a keyboard or screen, the only way to tell if something has gone wrong is to wait....................................................
Can ping the pi, but not ssh, so it must be doing something. Yes it is. It's churning out error logs or, if it goes wrong before the time has been set, the same log over and over again...
At least if it dies, it's hinting to take out the sd card and look at the log. 
For the eagle-eyed with a screen and keyboard, there's still the option to get into a shell.
> Don't loop forever after failure

- scripts/etc/init.d/rcS
Running v1.1.x branch on a Pi Zero W, I noticed that it was not identified as such.
rcS updated in line with current version of http://elinux.org/RPi_HardwareHistory#Board_Revision_History
> Identify Pi Zero W etc.

- scripts/etc/init.d/rcS
consoleblank=0 doesn't blank the screen.  Setting timeout to an hour, in this case, can decrease the timeout.
Using a slow sd card can extend the install time to over an hour.
> Don't override consoleblank=0 on cmdline

- build.sh
- scripts/etc/init.d/rcS
* Combined the two initramfs files into one
* Added log output while extracting the packages
* Some code cleanup
Since most files in the cpio are the same, except the kernel drivers, which are in a different folder, we can just merge the files into one.
This saves space on the /boot partition for future extensions.
@TODO: Test on devices with small memory (rpi1, rpi zero).
> Combined the two initramfs files into one

- build.sh
- update.sh
Changed both update.sh and build.sh kernel versions to 4.9.0-4 due 4.9.0-3 exist no more in upstream.
Signed-off-by: Sami Olmari <sami@olmari.fi>
> update.sh and build.sh kernel versions to 4.9.0-4

- build.sh
- update.sh
Change update.sh and build.sh kernel versions to 4.9.0-6
due 4.9.0-4 exist no more in upstream.
Signed-off-by: Sami Olmari <sami@olmari.fi>
> Change update.sh and build.sh kernel versions to 4.9.0-6
